"""Build the training manifest (txt lists + metadata.csv) from per-clip records.

Layout consumed by ``stm.data.I2VDatasetWithResize``::

    <dataset_root>/
      prompts.txt  videos.txt  fg.txt  fg-black.txt  bg.txt  masks.txt  images.txt
      metadata.csv
      <source>/videos/<id>.mp4          original clip (49 x 480 x 720 @ 16 fps)
      <source>/masks/<id>-00.mp4        binary mask video (white = foreground)
      <source>/fg/<id>-00.mp4           foreground layer on black
      <source>/bg/<id>-bg.mp4           background with the foreground removed (black hole)
      <source>/bg-inpainted/<id>-bg.mp4 MiniMax-Remover inpainted background (preferred by the loader)
      <source>/first_frames/<id>.png
      records/<id>.json                 per-clip state written by the pipeline
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd

from .config import DecomposerConfig

TXT_FILES = ("prompts.txt", "videos.txt", "fg.txt", "fg-black.txt", "bg.txt", "masks.txt", "images.txt")


def record_path(cfg: DecomposerConfig, clip_id: str) -> Path:
    return cfg.dataset_root / "records" / f"{clip_id}.json"


def load_records(cfg: DecomposerConfig) -> List[Dict]:
    rec_dir = cfg.dataset_root / "records"
    if not rec_dir.exists():
        return []
    records = []
    for p in sorted(rec_dir.glob("*.json")):
        try:
            records.append(json.loads(p.read_text()))
        except Exception:
            continue
    return records


def build_manifest(cfg: DecomposerConfig) -> Tuple[int, pd.DataFrame]:
    """Write txt lists + metadata.csv for every ``done`` record."""
    root = cfg.dataset_root
    records = [r for r in load_records(cfg) if r.get("status") == "done"]
    records.sort(key=lambda r: r["clip_id"])
    lines: Dict[str, List[str]] = {k: [] for k in TXT_FILES}
    rows = []
    lo, hi = cfg.fg_ratio_range
    for r in records:
        src, cid = r["source"], r["clip_id"]
        lines["prompts.txt"].append(r["caption"].replace("\n", " ").strip() or "None")
        lines["videos.txt"].append(f"{src}/videos/{cid}.mp4")
        lines["fg.txt"].append(f"{src}/fg/{cid}-00.mp4")
        lines["fg-black.txt"].append(f"{src}/fg/{cid}-00.mp4")
        lines["bg.txt"].append(f"{src}/bg/{cid}-bg.mp4")
        lines["masks.txt"].append(f"{src}/masks/{cid}-00.mp4")
        lines["images.txt"].append(f"{src}/first_frames/{cid}.png")
        is_training = bool(r.get("is_training", True))
        ratio = float(r["foreground_ratio"])
        main_train = is_training and r["num_frames"] > 35
        rows.append(
            {
                "vid_name": cid,
                "num_frames": r["num_frames"],
                "foreground_num": 1,
                "dataset_type": src,
                "height": r["height"],
                "width": r["width"],
                "is_training": is_training,
                "1fg-1bg": r["num_frames"] > 35,
                "foreground_ratio": ratio,
                "num_objects": r.get("num_objects", 1),
                "main_train": main_train,
                "main_train_foreground_volume": main_train and (lo <= ratio <= hi),
                "mask_source": r.get("mask_source", "seganymo"),
            }
        )
    root.mkdir(parents=True, exist_ok=True)
    for name, content in lines.items():
        (root / name).write_text("\n".join(content) + ("\n" if content else ""))
    df = pd.DataFrame(rows)
    df.to_csv(root / "metadata.csv", index=False)
    return len(records), df


def summarize(cfg: DecomposerConfig) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for r in load_records(cfg):
        key = r.get("status", "unknown")
        if key == "skipped":
            key = f"skipped:{r.get('reason', '?')}"
        counts[key] = counts.get(key, 0) + 1
    return counts


def write_dataset_readme(cfg: DecomposerConfig) -> str:
    """Write ``<dataset_root>/README.md`` describing the structure and current statistics."""
    import numpy as np

    root = cfg.dataset_root
    recs = load_records(cfg)
    done = [r for r in recs if r.get("status") == "done"]
    counts = summarize(cfg)
    by_src = {}
    for r in done:
        by_src[r["source"]] = by_src.get(r["source"], 0) + 1
    ratios = np.array([r["foreground_ratio"] for r in done]) if done else np.zeros(0)
    hist = np.histogram(ratios, bins=[0, 0.05, 0.1, 0.2, 0.3, 0.45])[0].tolist() if len(ratios) else []
    n_train = sum(1 for r in done if r.get("is_training", True))
    cap_len = np.array([len((r.get("caption") or "").split()) for r in done]) if done else np.zeros(0)
    t = [r["timings"].get("total") for r in done if r.get("timings", {}).get("total")]
    lines = [
        f"# {cfg.dataset_name} — StM multi-layer video dataset",
        "",
        "Generated by the StM Decomposer (`data_processing/generate_data.py`): InternVL2.5 captions, Segment-Any-Motion",
        "foreground masks (or ground-truth masks for VOS sources), MiniMax-Remover background inpainting.",
        f"Every clip is {cfg.num_frames} frames, {cfg.height}x{cfg.width}, {cfg.fps} fps.",
        "",
        "## Statistics",
        "",
        f"* decomposed clips (`done`): **{len(done)}** ({n_train} training, {len(done) - n_train} validation)",
        f"* per source: {by_src}",
        f"* record states: {counts}",
        f"* foreground ratio of done clips — bins [0,.05,.1,.2,.3,.45]: {hist}; mean {ratios.mean():.3f}" if len(ratios) else "",
        f"* caption length: mean {cap_len.mean():.0f} words" if len(cap_len) else "",
        f"* Decomposer time per clip: median {np.median(t):.0f} s" if t else "",
        "",
        "## Layout",
        "",
        "```",
        "prompts.txt videos.txt fg.txt fg-black.txt bg.txt masks.txt images.txt   aligned lists (paths relative to this folder)",
        "metadata.csv      vid_name, num_frames, foreground_num, dataset_type, height, width, is_training, 1fg-1bg,",
        "                  foreground_ratio, num_objects, main_train, main_train_foreground_volume, mask_source",
        "records/<id>.json per-clip provenance: source video, start frame, stride, caption, timings, status",
        "<source>/videos/<id>.mp4          original clip",
        "<source>/masks/<id>-00.mp4        binary foreground mask (white = fg)",
        "<source>/fg/<id>-00.mp4           foreground layer on black",
        "<source>/bg/<id>-bg.mp4           background with the foreground blacked out",
        "<source>/bg-inpainted/<id>-bg.mp4 inpainted clean-plate background (used for training/inference)",
        "<source>/first_frames/<id>.png    first frame",
        "```",
        "",
        "Training filter: `metadata.csv` column `main_train_foreground_volume` (single moving subject, >35 frames,",
        f"foreground ratio in [{cfg.fg_ratio_range[0]}, {cfg.fg_ratio_range[1]}]).",
    ]
    text = "\n".join(lines) + "\n"
    root.mkdir(parents=True, exist_ok=True)
    (root / "README.md").write_text(text)
    return text


def verify_dataset(cfg: DecomposerConfig, max_clips: Optional[int] = None) -> Dict:
    """Check that every ``done`` clip's files exist and have the expected frames / size / fps."""
    from .video_io import video_info

    expected = (cfg.num_frames, cfg.height, cfg.width)
    recs = [r for r in load_records(cfg) if r.get("status") == "done"]
    if max_clips:
        recs = recs[:max_clips]
    bad, sizes, n_files = [], [], 0
    for r in recs:
        src, cid = r["source"], r["clip_id"]
        files = {
            "video": cfg.dataset_root / src / "videos" / f"{cid}.mp4",
            "mask": cfg.dataset_root / src / "masks" / f"{cid}-00.mp4",
            "fg": cfg.dataset_root / src / "fg" / f"{cid}-00.mp4",
            "bg": cfg.dataset_root / src / "bg" / f"{cid}-bg.mp4",
            "bg_inpainted": cfg.dataset_root / src / "bg-inpainted" / f"{cid}-bg.mp4",
        }
        for kind, path in files.items():
            if not path.exists():
                bad.append((cid, kind, "missing"))
                continue
            try:
                n, fps, h, w = video_info(path)
            except Exception as exc:  # noqa: BLE001
                bad.append((cid, kind, f"unreadable: {exc!r}"[:80]))
                continue
            if (n, h, w) != expected or abs(fps - cfg.fps) > 0.5:
                bad.append((cid, kind, f"{n}x{h}x{w}@{fps:.1f}"))
            sizes.append(path.stat().st_size)
            n_files += 1
    import numpy as np

    report = {
        "clips_checked": len(recs),
        "files_checked": n_files,
        "bad": len(bad),
        "expected": f"{expected[0]}x{expected[1]}x{expected[2]}@{cfg.fps}fps",
        "file_size_MB_median": round(float(np.median(sizes)) / 1e6, 2) if sizes else 0,
        "file_size_MB_mean": round(float(np.mean(sizes)) / 1e6, 2) if sizes else 0,
        "total_GB": round(sum(sizes) / 1e9, 2),
    }
    print("[verify]", json.dumps(report))
    for b in bad[:20]:
        print("  bad:", b)
    return report
